export const jobCategories = [
  'Accounting',
  'Administration',
  'Advertising',
  'Agriculture',
  'Architecture',
  'Artificial Intelligence',
  'Automotive',
  'Aviation',
  'Banking',
  'Biotechnology',
  'Business Development',
  'Call Center',
  'Civil Engineering',
  'Cloud Computing',
  'Construction',
  'Consulting',
  'Content Writing',
  'Copywriting',
  'Customer Service',
  'Cyber Security',
  'Data Analyst',
  'Data Entry',
  'Data Science',
  'Database Administration',
  'Delivery Driver',
  'Design',
  'DevOps',
  'Digital Marketing',
  'E-Commerce',
  'Education',
  'Electrical Engineering',
  'Engineering',
  'Environmental Science',
  'Event Management',
  'Fashion',
  'Finance',
  'Food Services',
  'Freelance Jobs',
  'Full Stack Development',
  'Game Development',
  'Government Jobs',
  'Graphic Design',
  'Healthcare',
  'Hospitality',
  'Hotel Management',
  'Human Resources',
  'Industrial Engineering',
  'Information Technology',
  'Insurance',
  'Internship',
  'Internet of Things (IoT)',
  'IT Support',
  'Journalism',
  'Legal',
  'Logistics',
  'Machine Learning',
  'Manufacturing',
  'Marketing',
  'Mechanical Engineering',
  'Media',
  'Mobile App Development',
  'Network Engineering',
  'Nursing',
  'Operations',
  'Part-Time Jobs',
  'Pharmaceutical',
  'Photography',
  'Product Management',
  'Project Management',
  'Public Relations',
  'Quality Assurance',
  'Real Estate',
  'Receptionist',
  'Recruitment',
  'Remote Jobs',
  'Research',
  'Retail',
  'Robotics',
  'Sales',
  'Science',
  'SEO',
  'Security Services',
  'Skilled Trades',
  'Social Media Marketing',
  'Software Development',
  'Software Engineering',
  'Sports',
  'Supply Chain',
  'Teaching Jobs',
  'Technical Support',
  'Telecommunications',
  'Transportation',
  'Travel & Tourism',
  'UI/UX Design',
  'Video Editing',
  'Virtual Assistant',
  'Warehouse',
  'Web Development',
  'Work From Home Jobs',
  'Writing & Editing',
  'AI Jobs',
  'Blockchain',
  'Cryptocurrency',
  'Customer Success',
  'Technical Writing',
  'Translation',
  'Procurement',
  'Auditing',
  'Taxation',
  'Veterinary',
  'Mining',
  'Oil & Gas',
  'Renewable Energy',
  'Marine Services',
  'Government Contract Jobs',
  'NGO Jobs',
  'Non-Profit',
  'Remote Customer Service',
  'Remote Data Entry',
  'Remote Developer Jobs',
  'Remote Marketing Jobs',
  'Remote SEO Jobs',
]
