export interface BlogPageCardData {
  href: string
  title: string
  description: string
  keywords: string[]
  backgroundImage: string
  borderClass: string
  shadowClass: string
  labelText: string
  labelBgClass: string
  labelTextClass: string
  actionText: string
  category: string
  authorName: string
  authorInitials: string
  readTime: string
  publishedAt: string
  updatedAt: string
}

export const BLOG_PAGE_CARDS: BlogPageCardData[] = [
  {
    href: '/dhl-careers-uae-2026',
    title: 'DHL Careers UAE 2026',
    description: 'Explore DHL jobs in Dubai, Abu Dhabi, and across the UAE with salary insights, warehouse and logistics roles, benefits, hiring requirements, and direct application links.',
    keywords: ['DHL Careers', 'Logistics Jobs', 'Warehouse Jobs', 'Courier Jobs'],
    backgroundImage: '/DHL%20Careers%20UAE.png',
    borderClass: 'border-[#F2C94C]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(242,201,76,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#F2C94C]',
    labelTextClass: 'text-slate-900',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '6 min read',
    publishedAt: 'Jul 18, 2026',
    updatedAt: 'Jul 24, 2026'
  },
  {
    href: '/markq-trading-llc-storekeeper-dubai',
    title: 'MARKQ Trading LLC — Storekeeper (DIP 1, Dubai)',
    description: 'Entry-level storekeeper position at MARKQ Trading LLC in Dubai Investments Park. Salary AED 2,200–2,700/month. Easy Apply on Glassdoor.',
    keywords: ['Storekeeper', 'Warehouse Jobs', 'Dubai Jobs', 'Glassdoor'],
    backgroundImage: '/MARKQ%20Trading%20LLC.png',
    borderClass: 'border-[#0ea5a4]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(14,165,164,0.18)]',
    labelText: 'Featured Job',
    labelBgClass: 'bg-[#0ea5a4]',
    labelTextClass: 'text-white',
    actionText: 'Apply via Glassdoor',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '4 min read',
    publishedAt: 'Jul 18, 2026',
    updatedAt: 'Jul 24, 2026'
  },
  {
    href: '/noon-careers-uae-2026',
    title: 'Noon Careers UAE 2026',
    description: 'Explore the latest Noon careers in UAE with insights into e-commerce, technology, operations, logistics, customer service, and growth opportunities at one of the region’s fastest-growing companies.',
    keywords: ['Noon Careers', 'UAE Jobs', 'Ecommerce Jobs', 'Logistics Careers'],
    backgroundImage: '/Noon%20Careers%20UAE.png',
    borderClass: 'border-[#F2C94C]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(242,201,76,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#F2C94C]',
    labelTextClass: 'text-slate-900',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '5 min read',
    publishedAt: 'Jul 17, 2026',
    updatedAt: 'Jul 23, 2026'
  },
  {
    href: '/gems-education-careers-uae-2026',
    title: 'GEMS Education Careers UAE 2026',
    description: 'Explore GEMS Education teaching and corporate careers across the UAE, including school leadership, salary expectations, benefits, visa guidance, and official application guidance.',
    keywords: ['GEMS Education', 'UAE Jobs', 'Teaching Careers', 'School Leadership'],
    backgroundImage: '/UAE%20education%20careers%20(1).png',
    borderClass: 'border-[#FF6B35]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(255,107,53,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#FF6B35]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '6 min read',
    publishedAt: 'Jul 16, 2026',
    updatedAt: 'Jul 22, 2026'
  },
  {
    href: '/dp-world-careers-2026',
    title: 'DP World Careers 2026',
    description: 'Explore the latest DP World jobs in logistics, ports, supply chain, engineering, technology, warehouse operations, finance, and global operations.',
    keywords: ['DP World Careers', 'Logistics Jobs', 'Port Jobs', 'Supply Chain'],
    backgroundImage: '/DP%20World%20Careers.png',
    borderClass: 'border-[#00A651]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(0,166,81,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#00A651]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '5 min read',
    publishedAt: 'Jul 15, 2026',
    updatedAt: 'Jul 21, 2026'
  },
  {
    href: '/emirates-group-careers-uae-2026',
    title: 'Emirates Group Careers in UAE 2026',
    description: 'Discover the latest Emirates Group jobs, salary insights, benefits, and how to apply online for cabin crew, engineering, IT, and airport careers.',
    keywords: ['Emirates Careers', 'UAE Jobs', 'Cabin Crew', 'Engineering'],
    backgroundImage: '/Emirates%20Group%20Careers.png',
    borderClass: 'border-[#D71920]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(215,25,32,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#D71920]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '6 min read',
    publishedAt: 'Jul 14, 2026',
    updatedAt: 'Jul 20, 2026'
  },
  {
    href: '/warehouse-jobs-uae-2026',
    title: 'Warehouse Jobs in UAE 2026',
    description: 'Discover warehouse and logistics jobs across Dubai, Abu Dhabi, and the UAE with salary ranges, company hiring insights, requirements, and application tips.',
    keywords: ['Warehouse Jobs', 'Logistics Careers', 'DP World', 'DHL Jobs'],
    backgroundImage: '/Warehouse%20Jobs%20in%20UAE%202026.png',
    borderClass: 'border-[#0f766e]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(15,118,110,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#0f766e]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '5 min read',
    publishedAt: 'Jul 13, 2026',
    updatedAt: 'Jul 19, 2026'
  },
  {
    href: '/qatar-airways-careers-2026',
    title: 'Qatar Airways Careers 2026',
    description: 'Explore Qatar Airways job vacancies across cabin crew, pilots, engineering, IT, customer services, cargo, and corporate roles with competitive benefits.',
    keywords: ['Qatar Airways', 'Doha Jobs', 'Pilots', 'Cabin Crew'],
    backgroundImage: '/Qatar%20Airways%20Careers.png',
    borderClass: 'border-[#5C0E62]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(92,14,98,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#5C0E62]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '6 min read',
    publishedAt: 'Jul 12, 2026',
    updatedAt: 'Jul 18, 2026'
  },
  {
    href: '/genentech-careers-usa-2026',
    title: 'Genentech Careers USA 2026',
    description: 'Discover the latest Genentech biotech, research, marketing, engineering, and commercial roles across the United States with salary insights and application guidance.',
    keywords: ['Genentech Careers', 'Biotechnology Jobs', 'Marketing Jobs USA', 'Roche Careers'],
    backgroundImage: '/Genentech%20Careers%20USA%202026.png',
    borderClass: 'border-[#005EB8]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(0,94,184,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#005EB8]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '6 min read',
    publishedAt: 'Jul 11, 2026',
    updatedAt: 'Jul 17, 2026'
  },
  {
    href: '/shopify-careers-2026',
    title: 'Shopify Careers 2026',
    description: 'Explore Shopify remote jobs, internships, engineering roles, product opportunities, customer support positions, salaries, benefits, and the hiring process in one place.',
    keywords: ['Shopify Careers', 'Remote Jobs', 'Internships', 'Ecommerce Jobs'],
    backgroundImage: '/shopify-careers-2026.png',
    borderClass: 'border-[#95BF47]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(149,191,71,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#95BF47]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '6 min read',
    publishedAt: 'Jul 10, 2026',
    updatedAt: 'Jul 16, 2026'
  },
  {
    href: '/aecom-careers-uae-2026',
    title: 'AECOM Careers in UAE 2026',
    description: 'Explore the latest AECOM vacancies in Dubai, Abu Dhabi, and across the UAE with engineering, architecture, BIM, project management, HSE, and corporate career insights.',
    keywords: ['AECOM Careers', 'Engineering Jobs', 'Architecture Jobs', 'Infrastructure Jobs'],
    backgroundImage: '/aecom-careers-uae-2026.png',
    borderClass: 'border-[#005DAA]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(0,93,170,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#005DAA]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '6 min read',
    publishedAt: 'Jul 9, 2026',
    updatedAt: 'Jul 15, 2026'
  },
  {
    href: '/amazon-careers-2026',
    title: 'Amazon Careers 2026',
    description: 'Discover Amazon jobs worldwide, salary insights, hiring process details, remote opportunities, internship programs, leadership principles, and benefits in one premium guide.',
    keywords: ['Amazon Careers', 'Amazon Jobs', 'AWS Careers', 'Remote Jobs'],
    backgroundImage: '/amazon-careers-2026.png',
    borderClass: 'border-[#FF9900]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(255,153,0,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#FF9900]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '7 min read',
    publishedAt: 'Jul 8, 2026',
    updatedAt: 'Jul 14, 2026'
  },
  {
    href: '/fedex-careers-usa-2026',
    title: 'FedEx Careers USA 2026',
    description: 'Explore FedEx warehouse jobs, delivery driver opportunities, logistics careers, benefits, salaries, hiring process tips, and direct application guidance in one guide.',
    keywords: ['FedEx Careers', 'Logistics Jobs', 'Warehouse Jobs', 'Delivery Driver'],
    backgroundImage: '/fedex-careers-usa-2026.png',
    borderClass: 'border-[#FF6600]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(255,102,0,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#FF6600]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '5 min read',
    publishedAt: 'Jul 7, 2026',
    updatedAt: 'Jul 13, 2026'
  },
  {
    href: '/carrefour-hypermarket-careers-2026',
    title: 'Carrefour Hypermarket Careers 2026',
    description: 'Discover Carrefour retail, warehouse, customer service, supervisor, and store management opportunities with salary guidance, benefits, hiring requirements, and application tips.',
    keywords: ['Carrefour Careers', 'Retail Jobs', 'Warehouse Jobs', 'Customer Service Jobs'],
    backgroundImage: '/carrefour-hypermarket-careers.png',
    borderClass: 'border-[#ff6b2c]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(255,107,44,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#ff6b2c]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '6 min read',
    publishedAt: 'Jul 17, 2026',
    updatedAt: 'Jul 23, 2026'
  },
  {
    href: '/jobs/numero-senior-software-engineer-backend-remote-usa',
    title: 'Senior Software Engineer — Remote USA',
    description: 'Explore a remote backend engineering role with strong salary, high-growth company culture, and interview preparation advice for U.S.-based remote work.',
    keywords: ['Software Engineer', 'Remote USA', 'Backend', 'Senior Role'],
    backgroundImage: '/software-engineer-remote.png',
    borderClass: 'border-[#005EB8]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(0,94,184,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#005EB8]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '7 min read',
    publishedAt: 'Jul 15, 2026',
    updatedAt: 'Jul 22, 2026'
  },
  {
    href: '/uae-work-visa-sponsorship-guide-2026',
    title: 'UAE Work Visa Sponsorship Guide 2026',
    description: 'Get the full 2026 guide to UAE employer sponsorship, Golden Visa thresholds, application costs, and the documents you need to move to the UAE.',
    keywords: ['UAE Work Visa', 'Visa Sponsorship', 'Golden Visa', 'UAE Jobs'],
    backgroundImage: '/UAE%20Work%20Visa%20%26%20Sponsorship%20Guide.png',
    borderClass: 'border-[#0f766e]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(15,118,110,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#0f766e]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Visa guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '8 min read',
    publishedAt: 'Jul 14, 2026',
    updatedAt: 'Jul 21, 2026'
  }
]
