export interface BlogPageCardData {
  href: string
  title: string
  description: string
  keywords: string[]
  backgroundImage: string
  borderClass: string
  shadowClass: string
  labelText: string
  labelBgClass: string
  labelTextClass: string
  actionText: string
  category: string
  authorName: string
  authorInitials: string
  readTime: string
  publishedAt: string
  updatedAt: string
}

export const TRENDING_GUIDES = [
  '/visa/uae-employment-visa-guide',
  '/salary-guide/software-engineer-dubai-abu-dhabi-2026',
  '/career-resources/emiratisation-quota-2026-expat-jobseekers',
  '/career-insights/adnoc-careers-uae-2026',
] as const

export const BLOG_PAGE_CARDS: BlogPageCardData[] = [
  {
    href: '/al-futtaim-careers-uae',
    title: 'Al Futtaim Careers UAE 2026: Jobs, Salary & How to Apply',
    description: 'Complete guide to Al Futtaim careers in the UAE, covering automotive, retail, and corporate jobs, salary ranges, hiring requirements, and how to apply through A Future With Us.',
    keywords: ['al futtaim careers', 'al futtaim jobs dubai', 'al futtaim group careers', 'a future with us careers'],
    backgroundImage: '/Al Futtaim Careers UAE 2026.webp',
    borderClass: 'border-[#f97316]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(249,115,22,0.22)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#f97316]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '8 min read',
    publishedAt: 'Aug 16, 2026',
    updatedAt: 'Aug 16, 2026'
  },
  {
    href: '/lulu-hypermarket-careers-uae',
    title: 'LuLu Hypermarket Careers in UAE 2026',
    description: 'Complete guide to LuLu Hypermarket jobs, salaries, requirements, and the right way to apply across Dubai, Abu Dhabi, and Sharjah.',
    keywords: ['lulu hypermarket careers', 'lulu jobs dubai', 'lulu uae job vacancies', 'lulu recruitment'],
    backgroundImage: '/lulu-hypermarket-careers-uae.png',
    borderClass: 'border-[#0ea5e9]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(14,165,233,0.18)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#0ea5e9]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '8 min read',
    publishedAt: 'Aug 10, 2026',
    updatedAt: 'Aug 10, 2026'
  },
  {
    href: '/career-insights/adnoc-careers-uae-2026',
    title: 'ADNOC Careers UAE 2026: Apply, Salary & Which Companies Hire',
    description: 'A practical guide to ADNOC jobs in the UAE, including how to apply on jobs.adnoc.ae, expected salary ranges, group companies, and the Technical Academy pathway for UAE Nationals.',
    keywords: ['ADNOC careers', 'ADNOC jobs UAE', 'ADNOC salary', 'ADNOC vacancies'],
    backgroundImage: '/ADNOC%20oil%20and%20gas%20industrial.png',
    borderClass: 'border-[#0f766e]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(15,118,110,0.24)]',
    labelText: 'New',
    labelBgClass: 'bg-[#0f766e]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '11 min read',
    publishedAt: 'Aug 7, 2026',
    updatedAt: 'Aug 7, 2026'
  },
  {
    href: '/career-resources/payroll-job-description-salary-uae',
    title: 'Payroll Job Description & Salary in UAE 2026',
    description: 'Learn what payroll professionals do in the UAE, the common job titles, required skills, and realistic salary ranges for payroll clerks, officers, specialists, and managers.',
    keywords: ['Payroll job description', 'Payroll salary UAE', 'Payroll officer', 'Payroll manager'],
    backgroundImage: '/career-insights-payroll.png',
    borderClass: 'border-[#2563eb]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(37,99,235,0.22)]',
    labelText: 'New',
    labelBgClass: 'bg-[#2563eb]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '8 min read',
    publishedAt: 'Aug 4, 2026',
    updatedAt: 'Aug 4, 2026'
  },
  {
    href: '/dhl-careers-uae-2026',
    title: 'DHL Careers UAE 2026',
    description: 'Explore DHL jobs in Dubai, Abu Dhabi, and across the UAE with salary insights, warehouse and logistics roles, benefits, hiring requirements, and direct application links.',
    keywords: ['DHL Careers', 'Logistics Jobs', 'Warehouse Jobs', 'Courier Jobs'],
    backgroundImage: '/DHL%20Careers%20UAE.png',
    borderClass: 'border-[#F2C94C]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(242,201,76,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#F2C94C]',
    labelTextClass: 'text-slate-900',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '6 min read',
    publishedAt: 'Jul 18, 2026',
    updatedAt: 'Jul 24, 2026'
  },
  {
    href: '/markq-trading-llc-storekeeper-dubai',
    title: 'MARKQ Trading LLC — Storekeeper (DIP 1, Dubai)',
    description: 'Entry-level storekeeper position at MARKQ Trading LLC in Dubai Investments Park. Salary AED 2,200–2,700/month. Easy Apply on Glassdoor.',
    keywords: ['Storekeeper', 'Warehouse Jobs', 'Dubai Jobs', 'Glassdoor'],
    backgroundImage: '/MARKQ%20Trading%20LLC.png',
    borderClass: 'border-[#0ea5a4]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(14,165,164,0.18)]',
    labelText: 'Featured Job',
    labelBgClass: 'bg-[#0ea5a4]',
    labelTextClass: 'text-white',
    actionText: 'Apply via Glassdoor',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '4 min read',
    publishedAt: 'Jul 18, 2026',
    updatedAt: 'Jul 24, 2026'
  },
  {
    href: '/noon-careers-uae-2026',
    title: 'Noon Careers UAE 2026',
    description: 'Explore the latest Noon careers in UAE with insights into e-commerce, technology, operations, logistics, customer service, and growth opportunities at one of the region’s fastest-growing companies.',
    keywords: ['Noon Careers', 'UAE Jobs', 'Ecommerce Jobs', 'Logistics Careers'],
    backgroundImage: '/Noon%20Careers%20UAE.png',
    borderClass: 'border-[#F2C94C]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(242,201,76,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#F2C94C]',
    labelTextClass: 'text-slate-900',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '5 min read',
    publishedAt: 'Jul 17, 2026',
    updatedAt: 'Jul 23, 2026'
  },
  {
    href: '/gems-education-careers-uae-2026',
    title: 'GEMS Education Careers UAE 2026',
    description: 'Explore GEMS Education teaching and corporate careers across the UAE, including school leadership, salary expectations, benefits, visa guidance, and official application guidance.',
    keywords: ['GEMS Education', 'UAE Jobs', 'Teaching Careers', 'School Leadership'],
    backgroundImage: '/UAE%20education%20careers%20(1).png',
    borderClass: 'border-[#FF6B35]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(255,107,53,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#FF6B35]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '6 min read',
    publishedAt: 'Jul 16, 2026',
    updatedAt: 'Jul 22, 2026'
  },
  {
    href: '/dp-world-careers-2026',
    title: 'DP World Careers 2026',
    description: 'Explore the latest DP World jobs in logistics, ports, supply chain, engineering, technology, warehouse operations, finance, and global operations.',
    keywords: ['DP World Careers', 'Logistics Jobs', 'Port Jobs', 'Supply Chain'],
    backgroundImage: '/DP%20World%20Careers.png',
    borderClass: 'border-[#00A651]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(0,166,81,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#00A651]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '5 min read',
    publishedAt: 'Jul 15, 2026',
    updatedAt: 'Jul 21, 2026'
  },
  {
    href: '/emirates-group-careers-uae-2026',
    title: 'Emirates Group Careers in UAE 2026',
    description: 'Discover the latest Emirates Group jobs, salary insights, benefits, and how to apply online for cabin crew, engineering, IT, and airport careers.',
    keywords: ['Emirates Careers', 'UAE Jobs', 'Cabin Crew', 'Engineering'],
    backgroundImage: '/Emirates%20Group%20Careers.png',
    borderClass: 'border-[#D71920]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(215,25,32,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#D71920]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '6 min read',
    publishedAt: 'Jul 14, 2026',
    updatedAt: 'Jul 20, 2026'
  },
  {
    href: '/warehouse-jobs-uae-2026',
    title: 'Warehouse Jobs in UAE 2026',
    description: 'Discover warehouse and logistics jobs across Dubai, Abu Dhabi, and the UAE with salary ranges, company hiring insights, requirements, and application tips.',
    keywords: ['Warehouse Jobs', 'Logistics Careers', 'DP World', 'DHL Jobs'],
    backgroundImage: '/Warehouse%20Jobs%20in%20UAE%202026.png',
    borderClass: 'border-[#0f766e]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(15,118,110,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#0f766e]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '5 min read',
    publishedAt: 'Jul 13, 2026',
    updatedAt: 'Jul 19, 2026'
  },
  {
    href: '/qatar-airways-careers-2026',
    title: 'Qatar Airways Careers 2026',
    description: 'Explore Qatar Airways job vacancies across cabin crew, pilots, engineering, IT, customer services, cargo, and corporate roles with competitive benefits.',
    keywords: ['Qatar Airways', 'Doha Jobs', 'Pilots', 'Cabin Crew'],
    backgroundImage: '/Qatar%20Airways%20Careers.png',
    borderClass: 'border-[#5C0E62]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(92,14,98,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#5C0E62]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '6 min read',
    publishedAt: 'Jul 12, 2026',
    updatedAt: 'Jul 18, 2026'
  },
  {
    href: '/genentech-careers-usa-2026',
    title: 'Genentech Careers USA 2026',
    description: 'Discover the latest Genentech biotech, research, marketing, engineering, and commercial roles across the United States with salary insights and application guidance.',
    keywords: ['Genentech Careers', 'Biotechnology Jobs', 'Marketing Jobs USA', 'Roche Careers'],
    backgroundImage: '/Genentech%20Careers%20USA%202026.png',
    borderClass: 'border-[#005EB8]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(0,94,184,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#005EB8]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '6 min read',
    publishedAt: 'Jul 11, 2026',
    updatedAt: 'Jul 17, 2026'
  },
  {
    href: '/shopify-careers-2026',
    title: 'Shopify Careers 2026',
    description: 'Explore Shopify remote jobs, internships, engineering roles, product opportunities, customer support positions, salaries, benefits, and the hiring process in one place.',
    keywords: ['Shopify Careers', 'Remote Jobs', 'Internships', 'Ecommerce Jobs'],
    backgroundImage: '/shopify-careers-2026.png',
    borderClass: 'border-[#95BF47]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(149,191,71,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#95BF47]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '6 min read',
    publishedAt: 'Jul 10, 2026',
    updatedAt: 'Jul 16, 2026'
  },
  {
    href: '/aecom-careers-uae-2026',
    title: 'AECOM Careers in UAE 2026',
    description: 'Explore the latest AECOM vacancies in Dubai, Abu Dhabi, and across the UAE with engineering, architecture, BIM, project management, HSE, and corporate career insights.',
    keywords: ['AECOM Careers', 'Engineering Jobs', 'Architecture Jobs', 'Infrastructure Jobs'],
    backgroundImage: '/aecom-careers-uae-2026.png',
    borderClass: 'border-[#005DAA]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(0,93,170,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#005DAA]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '6 min read',
    publishedAt: 'Jul 9, 2026',
    updatedAt: 'Jul 15, 2026'
  },
  {
    href: '/amazon-careers-2026',
    title: 'Amazon Careers 2026',
    description: 'Discover Amazon jobs worldwide, salary insights, hiring process details, remote opportunities, internship programs, leadership principles, and benefits in one premium guide.',
    keywords: ['Amazon Careers', 'Amazon Jobs', 'AWS Careers', 'Remote Jobs'],
    backgroundImage: '/amazon-careers-2026.png',
    borderClass: 'border-[#FF9900]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(255,153,0,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#FF9900]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '7 min read',
    publishedAt: 'Jul 8, 2026',
    updatedAt: 'Jul 14, 2026'
  },
  {
    href: '/fedex-careers-usa-2026',
    title: 'FedEx Careers USA 2026',
    description: 'Explore FedEx warehouse jobs, delivery driver opportunities, logistics careers, benefits, salaries, hiring process tips, and direct application guidance in one guide.',
    keywords: ['FedEx Careers', 'Logistics Jobs', 'Warehouse Jobs', 'Delivery Driver'],
    backgroundImage: '/fedex-careers-usa-2026.png',
    borderClass: 'border-[#FF6600]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(255,102,0,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#FF6600]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '5 min read',
    publishedAt: 'Jul 7, 2026',
    updatedAt: 'Jul 13, 2026'
  },
  {
    href: '/carrefour-hypermarket-careers-2026',
    title: 'Carrefour Hypermarket Careers 2026',
    description: 'Discover Carrefour retail, warehouse, customer service, supervisor, and store management opportunities with salary guidance, benefits, hiring requirements, and application tips.',
    keywords: ['Carrefour Careers', 'Retail Jobs', 'Warehouse Jobs', 'Customer Service Jobs'],
    backgroundImage: '/carrefour-hypermarket-careers.png',
    borderClass: 'border-[#ff6b2c]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(255,107,44,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#ff6b2c]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '6 min read',
    publishedAt: 'Jul 17, 2026',
    updatedAt: 'Jul 23, 2026'
  },
  {
    href: '/career-insights/sharjah-aviation-services-careers',
    title: 'Sharjah Aviation Services Careers',
    description: 'Explore careers at Sharjah Aviation Services, including aviation operations, engineering, customer service, and support roles with salary expectations and application guidance.',
    keywords: ['Sharjah Aviation Services', 'Aviation careers', 'UAE aviation jobs', 'airport jobs'],
    backgroundImage: '/icon.svg',
    borderClass: 'border-[#2563eb]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(37,99,235,0.24)]',
    labelText: 'New guide',
    labelBgClass: 'bg-[#2563eb]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '6 min read',
    publishedAt: 'Aug 1, 2026',
    updatedAt: 'Aug 1, 2026'
  },
  {
    href: '/visa/uae-overstay-fine-2026',
    title: 'UAE Overstay Fine 2026',
    description: 'Understand the new AED 50 per day overstay rule, the removed grace period for tourist visas, and what to do if you are already overstaying.',
    keywords: ['UAE overstay fine', 'visa grace period', 'overstay calculator'],
    backgroundImage: '/icon.svg',
    borderClass: 'border-[#0f766e]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(15,118,110,0.24)]',
    labelText: 'New guide',
    labelBgClass: 'bg-[#0f766e]',
    labelTextClass: 'text-white',
    actionText: 'Read guide',
    category: 'Visa guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '7 min read',
    publishedAt: 'Jul 1, 2026',
    updatedAt: 'Jul 2, 2026'
  },
  {
    href: '/visa/uae-jobseeker-visa-2026',
    title: 'UAE Jobseeker Visa 2026',
    description: 'Learn how the new ICP jobseeker visa works, who it is for, how to apply, and how it connects to an employment visa.',
    keywords: ['jobseeker visa', 'UAE job search visa', 'ICP jobseeker visa'],
    backgroundImage: '/icon.svg',
    borderClass: 'border-[#2563eb]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(37,99,235,0.24)]',
    labelText: 'New guide',
    labelBgClass: 'bg-[#2563eb]',
    labelTextClass: 'text-white',
    actionText: 'Read guide',
    category: 'Visa guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '7 min read',
    publishedAt: 'Jul 3, 2026',
    updatedAt: 'Jul 4, 2026'
  },
  {
    href: '/visa/uae-freelance-permit-vs-employment-visa',
    title: 'UAE Freelance Permit vs Employment Visa 2026',
    description: 'Compare the freelance permit and employer-sponsored employment visa for remote workers, freelancers, and UAE-based employees.',
    keywords: ['freelance permit', 'remote work visa', 'employment visa UAE'],
    backgroundImage: '/icon.svg',
    borderClass: 'border-[#7c3aed]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(124,58,237,0.24)]',
    labelText: 'New guide',
    labelBgClass: 'bg-[#7c3aed]',
    labelTextClass: 'text-white',
    actionText: 'Read guide',
    category: 'Visa guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '7 min read',
    publishedAt: 'Jul 5, 2026',
    updatedAt: 'Jul 6, 2026'
  },
  {
    href: '/visa/uae-visa-cancellation-grace-period-2026',
    title: 'UAE Visa Cancellation Grace Period 2026',
    description: 'Learn how the 30 to 180 day grace period works after visa cancellation, what it depends on, and what to do next.',
    keywords: ['visa cancellation grace period', 'UAE grace period', 'job loss visa grace'],
    backgroundImage: '/icon.svg',
    borderClass: 'border-[#dc2626]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(220,38,38,0.24)]',
    labelText: 'New guide',
    labelBgClass: 'bg-[#dc2626]',
    labelTextClass: 'text-white',
    actionText: 'Read guide',
    category: 'Visa guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '7 min read',
    publishedAt: 'Jul 7, 2026',
    updatedAt: 'Jul 8, 2026'
  },
  {
    href: '/salary-guide/software-engineer-dubai-abu-dhabi-2026',
    title: 'Software Engineer Salary in Dubai vs Abu Dhabi 2026',
    description: 'Compare software engineer pay in Dubai and Abu Dhabi, and understand how free zone vs mainland structures affect real compensation.',
    keywords: ['software engineer salary', 'Dubai salary', 'Abu Dhabi salary'],
    backgroundImage: '/icon.svg',
    borderClass: 'border-[#0f766e]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(15,118,110,0.24)]',
    labelText: 'New guide',
    labelBgClass: 'bg-[#0f766e]',
    labelTextClass: 'text-white',
    actionText: 'Read guide',
    category: 'Salary guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '7 min read',
    publishedAt: 'Jul 9, 2026',
    updatedAt: 'Jul 10, 2026'
  },
  {
    href: '/salary-guide/nurse-salary-uae-dha-haad-moh-2026',
    title: 'Nurse Salary in UAE 2026',
    description: 'Compare DHA, HAAD/DOH, and MOH licensing paths and how they affect nursing pay across the UAE.',
    keywords: ['nurse salary', 'UAE nursing', 'DHA vs HAAD'],
    backgroundImage: '/icon.svg',
    borderClass: 'border-[#2563eb]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(37,99,235,0.24)]',
    labelText: 'New guide',
    labelBgClass: 'bg-[#2563eb]',
    labelTextClass: 'text-white',
    actionText: 'Read guide',
    category: 'Salary guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '7 min read',
    publishedAt: 'Jul 11, 2026',
    updatedAt: 'Jul 12, 2026'
  },
  {
    href: '/salary-guide/teacher-salary-dubai-curriculum-2026',
    title: 'Teacher Salary in Dubai Private Schools 2026',
    description: 'See how British, IB, and American curriculum schools compare on teacher pay, benefits, and package value in Dubai.',
    keywords: ['teacher salary Dubai', 'IB teacher pay', 'American curriculum salary'],
    backgroundImage: '/icon.svg',
    borderClass: 'border-[#f59e0b]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(245,158,11,0.24)]',
    labelText: 'New guide',
    labelBgClass: 'bg-[#f59e0b]',
    labelTextClass: 'text-white',
    actionText: 'Read guide',
    category: 'Salary guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '7 min read',
    publishedAt: 'Jul 13, 2026',
    updatedAt: 'Jul 14, 2026'
  },
  {
    href: '/salary-guide/entry-level-salary-uae-fresh-graduates-2026',
    title: 'Entry-Level Salary in UAE 2026',
    description: 'Understand what fresh graduates can realistically expect to earn in the UAE, by field and by employer type.',
    keywords: ['entry level salary', 'fresh graduate salary', 'UAE first job'],
    backgroundImage: '/icon.svg',
    borderClass: 'border-[#7c3aed]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(124,58,237,0.24)]',
    labelText: 'New guide',
    labelBgClass: 'bg-[#7c3aed]',
    labelTextClass: 'text-white',
    actionText: 'Read guide',
    category: 'Salary guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '7 min read',
    publishedAt: 'Jul 15, 2026',
    updatedAt: 'Jul 16, 2026'
  },
  {
    href: '/salary-guide/g42-careers-uae-2026',
    title: 'G42 Careers UAE 2026',
    description: 'Explore AI, cloud, cybersecurity and tech jobs at Abu Dhabi’s G42 group, with application guidance, salary expectations and benefits for 2026.',
    keywords: ['G42 careers', 'AI jobs UAE', 'cloud engineer jobs UAE', 'G42 Abu Dhabi'],
    backgroundImage: '/icon.svg',
    borderClass: 'border-[#7c3aed]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(124,58,237,0.24)]',
    labelText: 'New guide',
    labelBgClass: 'bg-[#7c3aed]',
    labelTextClass: 'text-white',
    actionText: 'Read guide',
    category: 'Salary guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '9 min read',
    publishedAt: 'Jul 23, 2026',
    updatedAt: 'Jul 24, 2026'
  },
  {
    href: '/career-resources/uae-experience-certificate-guide',
    title: 'UAE Experience Certificate Guide',
    description: 'Learn how to request a UAE experience certificate after resignation, what it should include, and use a sample request email.',
    keywords: ['experience certificate', 'UAE experience letter', 'employment certificate'],
    backgroundImage: '/icon.svg',
    borderClass: 'border-[#0f766e]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(15,118,110,0.24)]',
    labelText: 'New guide',
    labelBgClass: 'bg-[#0f766e]',
    labelTextClass: 'text-white',
    actionText: 'Read guide',
    category: 'Career resources',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '7 min read',
    publishedAt: 'Jul 17, 2026',
    updatedAt: 'Jul 18, 2026'
  },
  {
    href: '/career-resources/emiratisation-quota-2026-expat-jobseekers',
    title: 'Emiratisation Quota 2026 for Expat Job Seekers',
    description: 'Understand how the UAE Emiratisation quota affects expat applicants, which employers are affected, and how to position your profile strategically.',
    keywords: ['Emiratisation quota', 'UAE hiring rules', 'expat job seekers', 'MOHRE Emiratisation'],
    backgroundImage: '/icon.svg',
    borderClass: 'border-[#2563eb]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(37,99,235,0.24)]',
    labelText: 'New guide',
    labelBgClass: 'bg-[#2563eb]',
    labelTextClass: 'text-white',
    actionText: 'Read guide',
    category: 'Career resources',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '7 min read',
    publishedAt: 'Jul 19, 2026',
    updatedAt: 'Jul 20, 2026'
  },
  {
    href: '/career-resources/negotiate-salary-uae-job-offer',
    title: 'How to Negotiate a UAE Job Offer',
    description: 'Learn how to evaluate housing, flights, medical coverage, and gratuity so you can negotiate the full UAE salary package, not just base pay.',
    keywords: ['UAE salary package', 'housing allowance', 'gratuity calculation', 'job offer negotiation'],
    backgroundImage: '/icon.svg',
    borderClass: 'border-[#f59e0b]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(245,158,11,0.24)]',
    labelText: 'New guide',
    labelBgClass: 'bg-[#f59e0b]',
    labelTextClass: 'text-white',
    actionText: 'Read guide',
    category: 'Career resources',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '7 min read',
    publishedAt: 'Jul 21, 2026',
    updatedAt: 'Jul 22, 2026'
  },
  {
    href: '/jobs/numero-senior-software-engineer-backend-remote-usa',
    title: 'Senior Software Engineer — Remote USA',
    description: 'Explore a remote backend engineering role with strong salary, high-growth company culture, and interview preparation advice for U.S.-based remote work.',
    keywords: ['Software Engineer', 'Remote USA', 'Backend', 'Senior Role'],
    backgroundImage: '/software-engineer-remote.png',
    borderClass: 'border-[#005EB8]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(0,94,184,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#005EB8]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Career guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '7 min read',
    publishedAt: 'Jul 15, 2026',
    updatedAt: 'Jul 22, 2026'
  },
  {
    href: '/uae-work-visa-sponsorship-guide-2026',
    title: 'UAE Work Visa Sponsorship Guide 2026',
    description: 'Get the full 2026 guide to UAE employer sponsorship, Golden Visa thresholds, application costs, and the documents you need to move to the UAE.',
    keywords: ['UAE Work Visa', 'Visa Sponsorship', 'Golden Visa', 'UAE Jobs'],
    backgroundImage: '/UAE%20Work%20Visa%20%26%20Sponsorship%20Guide.png',
    borderClass: 'border-[#0f766e]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(15,118,110,0.24)]',
    labelText: 'Featured',
    labelBgClass: 'bg-[#0f766e]',
    labelTextClass: 'text-white',
    actionText: 'Read article',
    category: 'Visa guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '8 min read',
    publishedAt: 'Jul 1, 2026',
    updatedAt: 'Jul 2, 2026'
  },
  {
    href: '/visa/uae-employment-visa-guide',
    title: 'UAE Employment Visa Guide',
    description: 'Understand the UAE employment visa process, eligibility requirements, document checklist, and timelines for securing a work visa in the Emirates.',
    keywords: ['UAE Employment Visa', 'Work Visa', 'Employment Visa', 'UAE Jobs'],
    backgroundImage: '/UAE%20Work%20Visa%20%26%20Sponsorship%20Guide.png',
    borderClass: 'border-[#0f766e]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(15,118,110,0.24)]',
    labelText: 'Visa Guide',
    labelBgClass: 'bg-[#0f766e]',
    labelTextClass: 'text-white',
    actionText: 'Read guide',
    category: 'Visa guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '5 min read',
    publishedAt: 'Jul 3, 2026',
    updatedAt: 'Jul 4, 2026'
  },
  {
    href: '/visa/uae-golden-visa-guide',
    title: 'UAE Golden Visa Guide',
    description: 'Learn about the UAE Golden Visa categories, eligibility thresholds, benefits, and the application steps for long-term residency.',
    keywords: ['Golden Visa', 'UAE Residency', 'Long-Term Visa', 'UAE Jobs'],
    backgroundImage: '/UAE%20Work%20Visa%20%26%20Sponsorship%20Guide.png',
    borderClass: 'border-[#0f766e]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(15,118,110,0.24)]',
    labelText: 'Visa Guide',
    labelBgClass: 'bg-[#0f766e]',
    labelTextClass: 'text-white',
    actionText: 'Read guide',
    category: 'Visa guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '5 min read',
    publishedAt: 'Jul 5, 2026',
    updatedAt: 'Jul 6, 2026'
  },
  {
    href: '/visa/uae-family-sponsorship-guide',
    title: 'UAE Family Sponsorship Guide',
    description: 'Explore how family sponsorship works in the UAE, including eligibility, required documents, and common application questions.',
    keywords: ['UAE Family Sponsorship', 'Family Visa', 'Visa Guide', 'UAE Residency'],
    backgroundImage: '/UAE%20Work%20Visa%20%26%20Sponsorship%20Guide.png',
    borderClass: 'border-[#0f766e]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(15,118,110,0.24)]',
    labelText: 'Visa Guide',
    labelBgClass: 'bg-[#0f766e]',
    labelTextClass: 'text-white',
    actionText: 'Read guide',
    category: 'Visa guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '4 min read',
    publishedAt: 'Jul 7, 2026',
    updatedAt: 'Jul 8, 2026'
  },
  {
    href: '/visa/uae-work-permit-guide',
    title: 'UAE Work Permit Guide',
    description: 'Get a clear overview of UAE work permit rules, employer responsibilities, and the steps to obtain a legal work authorization.',
    keywords: ['UAE Work Permit', 'Work Authorization', 'Visa Guide', 'UAE Jobs'],
    backgroundImage: '/UAE%20Work%20Visa%20%26%20Sponsorship%20Guide.png',
    borderClass: 'border-[#0f766e]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(15,118,110,0.24)]',
    labelText: 'Visa Guide',
    labelBgClass: 'bg-[#0f766e]',
    labelTextClass: 'text-white',
    actionText: 'Read guide',
    category: 'Visa guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '4 min read',
    publishedAt: 'Jul 28, 2026',
    updatedAt: 'Jul 29, 2026'
  },
  {
    href: '/visa/uae-golden-visa-property-threshold-2026',
    title: 'UAE Golden Visa Property Threshold 2026',
    description: 'Understand the 2026 property threshold changes for UAE Golden Visas, including off-plan rules, joint ownership, and what to do if you fall short.',
    keywords: ['Golden Visa', 'UAE Golden Visa Property Threshold 2026', 'Property Rules', 'Visa Guide'],
    backgroundImage: '/UAE%20Work%20Visa%20%26%20Sponsorship%20Guide.png',
    borderClass: 'border-[#0f766e]',
    shadowClass: 'shadow-[0_25px_70px_-24px_rgba(15,118,110,0.24)]',
    labelText: 'New Article',
    labelBgClass: 'bg-[#0f766e]',
    labelTextClass: 'text-white',
    actionText: 'Read guide',
    category: 'Visa guide',
    authorName: 'CareerHunt',
    authorInitials: 'CH',
    readTime: '6 min read',
    publishedAt: 'Jun 14, 2026',
    updatedAt: 'Jun 15, 2026'
  }
]
